---
title: "Exploratory Data Analysis"
author: "Robert"
date: "2/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r, message=FALSE}
library(ggplot2)
library(ggthemes)
library(Hmisc)
library(purrr)
library(dplyr)
library(tidyr)
library(tibble)
```

## Load Datasets

```{r}
df <- read.csv('data/CaseStudy2-data.csv')

head(df)
```

## Find Correlations in Dataset

```{r fig.width=10, fig.height=10, warning=FALSE}

# create dataframe of numerical columns
numeric_df <- df %>% 
  # select only numeric columns
  select(where(is.numeric)) %>%
  # remove irrelevant columns
  select(-c(ID, EmployeeCount, StandardHours))

# function to create a list of dataframes of correlations, n, and p-values
format_corr_df <- function(df, alpha) { 
  
  rcorr_df <- rcorr(as.matrix(df))
  mapped_df <- (map(rcorr_df, ~data.frame(.x)))
  
  res <- mapped_df %>% map(~rownames_to_column(.x, var="Measure_1")) %>%
  map(~pivot_longer(.x, -Measure_1, "Measure_2")) %>%
  bind_rows(.id = "id") %>%
  pivot_wider(names_from = id, values_from = value) %>%
  mutate(
    sig_p = ifelse(P < alpha, T, F),
    p_if_sig = ifelse(P < alpha, P, NA),
    r_if_sig = ifelse(P < alpha, r, NA))
  
  return (res)
}

# create a dataframe of 
corr_df <- format_corr_df(numeric_df, 0.05)


corr_df %>%
  ggplot(aes(x = Measure_1, y = Measure_2, fill = r, label=round(r_if_sig,2))) +
  geom_tile() +
  labs(
    x = NULL, 
    y = NULL, 
    fill = "Pearson's\nCorrelation", 
    title="Correlations in Employee Attrition",
    subtitle="Only significant Pearson's correlation coefficients shown") +
  scale_fill_gradient2(mid="#FBFEF9",low="#0C6291",high="#A63446", limits=c(-1,1)) +
  geom_text(size=3) +
  theme_classic() +
  scale_x_discrete(expand=c(0,0)) +
  scale_y_discrete(expand=c(0,0)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))




corr_df$Measures <- apply(corr_df[,c("Measure_1", "Measure_2")], 1, function(x) paste(sort(x), collapse = "-"))


corr_df

corr_df %>%
  filter(sig_p, !duplicated(Measures)) %>%
  arrange(desc(r)) %>%
  head(10)
```

# Find the Overall Attrition Rate for the Dataset

```{r}
# calculate the percentage total attrition rate for the sample dataset
total_attr_df <- df %>% 
  group_by(Attrition) %>%
  summarise(count = n()) %>%
  mutate(freq = round(count / sum(count), 3))

# save the attrition rate in a variable
total_attr_rate <- total_attr_df[total_attr_df$Attrition == 'Yes', 'freq']

# print the result
paste0('The total attrition rate for the dataset is ', total_attr_rate * 100, '%')
```